server:
  port: 8762
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: QUIZ-SERVICE
          uri: lb://QUIZ-SERVICE
          predicates:
            - name: Path
              args:
                pattern: /api/v1/quiz/**
        - id: QUESTION-SERVICE
          uri: lb://QUESTION-SERVICE
          predicates:
            - name: Path
              args:
                pattern: /api/v1/question/**
      
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    prefer-ip-address: false
    hostName: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
