spring:
  application:
    name: SERVICE-REGISTRY

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
      # If set to true, Eureka server will not immediately evict instances that are not sending heartbeats.
      enableSelfPreservation: false 
