server:
  port: 9001

spring:
  application:
    name: QUIZ-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: false
    hostName: localhost
    instance-id: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

      
springdoc:
  swagger-ui:
    path: /swagger-ui